version: '3.8'

services:
  smart-shopper-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./internal/data/prices.json:/app/internal/data/prices.json
    env_file:
      - .env
    restart: unless-stopped
